### ISSUE TITLE
IDE List 

### ISSUE THREAD

**Issue by BMeridian** [logston/NYCPythonSOH#1]
http://wingware.com/downloads/wingide-101/5.0.9-1
https://code.google.com/p/spyderlib/

**Comment by logston** [comment]
Awesome, can you issue a PR with these additions?

**Comment by dillonko** [comment]
Thereis also another tool I have been using called Atom. You can get it from atom.io, even sync it with your github. Atom is similar sublime text. But it is more feature friendly. Everyone should try it.

**Comment by logston** [comment]
Awesome, can you issue a PR with this addition?

**Comment by dillonko** [comment]
Hey Paul,
Im not sure but I can check it out for you. Are you doing anything new at
the meetup today.

**Comment by logston** [comment]
Hey @dillonko, a PR with an addition of a link to Atom would be fine. No other research necessary.

Nothing new today. Same great meetup :)

**Comment by dillonko** [comment]
Ok I will be at the one you have tomorrow.
